[project]
name = "va"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pavel Reshetnikov", email = "pavelresh@yandex.ru" }
]
requires-python = ">=3.14"
dependencies = [
    "livekit-wakeword>=0.2.1",
    "numpy>=2.5.2",
    "piper-tts>=1.8.0",
    "pywhispercpp>=1.5.1",
    "silero-vad-notorch>=6.2.1.1",
    "sounddevice>=0.5.6",
    "soundfile>=0.14.0",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
